name: pull_request

on:
  pull_request:
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - main

env:
  SQLX_OFFLINE: true

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.76
        with:
          components: rustfmt

      - run: cargo fmt --all --check

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.76
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - run: cargo clippy --workspace --all-targets

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.76

      - uses: Swatinem/rust-cache@v2

      # Run tests with `gc_tombstone` on so that object IDs don't get reused in
      # snapshot test output.
      - run: cargo test --workspace --no-fail-fast --features='gc_tombstone'
